[package]
name = "valence-coprocessor-app-deployer"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "The Valence co-processor domain definition."

[dependencies]
anyhow.workspace = true
base64 = { version = "0.22.1", default-features = false, features = ["alloc"] }
clap = { version = "4.5.38", features = ["cargo"] }
reqwest = { version = "0.12.15", features = ["blocking", "json"] }
serde_json.workspace = true
