# Generated by crate2nix 0.14.1 from Cargo.toml
# Do not edit this file manually
{ lib, buildRustCrateHelpers, buildRustCrate, fetchCratesIo, fetchCrate, ... }:
rec {
  crates = lib.mapAttrs (_: value: buildRustCrate value) {
    valence-coprocessor-app-circuit = {
      crateName = "valence-coprocessor-app-circuit";
      version = "0.4.2";
      edition = "2021";
      src = ./crates/circuit;
      authors = ["Timewave Labs"];
      license = "Apache-2.0";
      libName = "valence_coprocessor_app_circuit";
      crateType = [ "cdylib" "rlib" ];
      dependencies = [
        {
          name = "valence-coprocessor";
          version = "0.3.7";
          registry = "registry+https://github.com/rust-lang/crates.io-index";
        }
      ];
    };
    
    valence-coprocessor-app-controller = {
      crateName = "valence-coprocessor-app-controller";
      version = "0.4.2";
      edition = "2021";
      src = ./crates/controller;
      authors = ["Timewave Labs"];
      license = "Apache-2.0";
      libName = "valence_coprocessor_app_controller";
      crateType = [ "cdylib" "rlib" ];
      dependencies = [
        {
          name = "anyhow";
          version = "1.0.83";
          registry = "registry+https://github.com/rust-lang/crates.io-index";
        }
        {
          name = "serde_json";
          version = "1.0.140";
          registry = "registry+https://github.com/rust-lang/crates.io-index";
        }
        {
          name = "valence-coprocessor";
          version = "0.3.7";
          registry = "registry+https://github.com/rust-lang/crates.io-index";
        }
        {
          name = "valence-coprocessor-wasm";
          version = "0.3.7";
          registry = "registry+https://github.com/rust-lang/crates.io-index";
        }
      ];
    };
  };
}