[valence]
name = "valence-app"
version = "0.1.0"
artifacts = ".valence/coprocessor/artifacts"

[circuit.app]
circuit = "valence-coprocessor-app-circuit"
controller = "valence-coprocessor-app-controller"
