[target.wasm32-unknown-unknown]
rustflags = [
  "--cfg=web_sys_unstable_apis",
  "-C", "link-arg=--import-memory",
]

[build]
target = "wasm32-unknown-unknown"

[unstable]
build-std = ["panic_abort", "std"] 