[package]
name = "valence-coprocessor-app-program"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "The Valence co-processor program definition."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow.workspace = true
serde_json.workspace = true
valence-coprocessor.workspace = true
valence-coprocessor-wasm.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wee_alloc = "0.4.5"
