name: build circuits

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: >
      ${{ matrix.os }}
      ${{ matrix.docker && 'with docker' || 'without docker' }}
      ${{ matrix.nix && 'with nix' || 'without nix' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macos-latest", "ubuntu-latest" ]
        nix: [ true, false ]
        docker: [ true, false ]
        exclude:
          nix: false
          docker: false
    steps:
      - uses: actions/checkout@v4
      - name: Install nix
        if: matrix.nix
        uses: nixbuild/nix-quick-install-action@v32
      - uses: mathio/gha-cleanup@v1
        with:
          remove-browsers: true
      - name: Remove docker
        if: ! matrix.docker
        run: rm /usr/bin/docker
      - name: Build circuits
        run: ./build-circuits.sh
        env:
          NIX_ARGS: "-vL"
