name: build circuits

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    name: >
      ${{ matrix.os }}
      ${{ matrix.docker && 'with docker' || 'without docker' }}
      ${{ matrix.nix && 'with nix' || 'without nix' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macos-latest", "ubuntu-latest" ]
        nix: [ true, false ]
        docker: [ true, false ]
        exclude:
          # Won't work, either nix or docker is needed
          - nix: false
            docker: false
          # Unnecessary, script defaults to nix when both are available
          - nix: true
            docker: true
    steps:
      - uses: actions/checkout@v4
      - name: Install nix
        if: matrix.nix
        uses: nixbuild/nix-quick-install-action@v32
      - uses: mathio/gha-cleanup@v1
        with:
          remove-browsers: true
      - name: Install docker on MacOS
        if: ${{ matrix.os == "macos-latest" && matrix.docker }}
        run: |
          brew install docker colima
          colima start
      - name: Remove docker
        if: ${{ ! matrix.docker }}
        run: sudo rm -f $(which docker)
      - name: Build circuits
        run: ./build-circuits.sh
        env:
          NIX_ARGS: "-vL"
