authorizations = "neutron193003jwk7dfcfhrwkm88eqyrwzkc6mny4d4rhx4ufg9yzpaxsshqn70k9h"
processor = "neutron10phqc83lag5m2pltnwxeffnwkdx0ygkkxkuz9qrs5ehpc4gskfdsxcas5x"
cw20 = "neutron1m6mft6k2c7cd6lsr4damvf3y742y36cvl404n6pvp3g2vpjmkvqq7ja9k3"
