authorizations = "neutron1ukjfq0s3zwkw05pe33er5fxc7alm32s4muckmta9dfd3sdsevytsmucrzs"
processor = "neutron155eezscx83v7raveeseuzq5eqeewurwp6mqgnkkvnd8t9k96pktsg7hvrl"
cw20 = "neutron1mx36wgsqasgdg8ktpkar6qf5j5keeddfcz90llvcngkfcpel8kcs8l9mzj"
