authorizations = "neutron1q7mee66pmfd6rjydghpqptj6r86pk8ewwplzm2nn9nahxkhf2f6sqltq5x"
processor = "neutron1c4xuxjvylg7lvsvfkjteesudrrgcr6hjvsjvkxex9wag2rwt45kqvugse3"
cw20 = "neutron196utlyqfmtsg7r7rkfdmzd8qhvdg9k250mn8e4zna3d8hpv8wwlqc8ylh9"
