authorizations = "neutron1d3ww47nadgwpaxu4naauvswf366a27qp6pz3zjkafyn9rfwk2hds6mrcds"
processor = "neutron1578hcn490kj4qth3gf095zldqldamsmdfwl0g96l92agm3pzmytqeglx5a"
cw20 = "neutron17v7gkaa5l4n2hhq3ymk2x0g5u4anmztlpc9ef9sdfm7whptj4xpqnj26rd"
