grpc_url = "http://rpc.neutron.quokkastake.io"
grpc_port = "9090"
chain_id = "neutron-1"
authorizations = "neutron1rzz8wxe7tnn8f9um3tx7dqs20qnew54sdqyk38npye6hcp9asfhqepvx4z"
processor = "neutron1dfswy7heg00wsve94h7j4athndekzeyutuqgllehgqhg5wmaqersap3scq"
cw20 = "neutron1evtttxy89n4zjlcypcwqsprmslhs7zeszjc534gmqhn5edc9djeq9sh4tt"
coprocessor_app_id = "b65ee588928b74dc9fae6c85f60c7a9f311c16cd2e467ac4bb82ea27aa27c241"
