grpc_url = "http://rpc.neutron.quokkastake.io"
grpc_port = "9090"
chain_id = "neutron-1"
authorizations = "neutron193003jwk7dfcfhrwkm88eqyrwzkc6mny4d4rhx4ufg9yzpaxsshqn70k9h"
processor = "neutron10phqc83lag5m2pltnwxeffnwkdx0ygkkxkuz9qrs5ehpc4gskfdsxcas5x"
cw20 = "neutron1m6mft6k2c7cd6lsr4damvf3y742y36cvl404n6pvp3g2vpjmkvqq7ja9k3"
coprocessor_app_id = "ba0aeb80f155a8340309ab7b9cbf23e995fc4f8e07c6a0a12876937c8196cf20"
