grpc_url = "http://rpc.neutron.quokkastake.io"
grpc_port = "9090"
chain_id = "neutron-1"
authorizations = "neutron1d3ww47nadgwpaxu4naauvswf366a27qp6pz3zjkafyn9rfwk2hds6mrcds"
processor = "neutron1578hcn490kj4qth3gf095zldqldamsmdfwl0g96l92agm3pzmytqeglx5a"
cw20 = "neutron17v7gkaa5l4n2hhq3ymk2x0g5u4anmztlpc9ef9sdfm7whptj4xpqnj26rd"
coprocessor_app_id = "a903358e531a0a048b0242d4c7cd904df8df6c9e7f0c6dec95673ebd0aa6da54"
