grpc_url = "http://rpc.neutron.quokkastake.io"
grpc_port = "9090"
chain_id = "neutron-1"
authorizations = "neutron1fkfmpxv5hyd3kqedtszjz87vw5qww3zyzyx5gsm5ku0xxgq2svjq8rq0zk"
processor = "neutron13d280e6yy4sgnfmdht44lkyhwwyzakg3zy8a56dpscgs8u54wldqkkxh4c"
cw20 = "neutron1v7nhn0e8yw9l30e86529szsfzyh85p4426uqqevwu8s75y4400pqg0vmmk"
coprocessor_app_id = "e687bb60acce7644c7399d59efdce31d246a57f2651f85bdac4efa383d72d3db"
